<a href="https://colab.research.google.com/github/swapnil-kahar/ml-project/blob/main/swapnil_kahar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing the important libraries 

In [3]:
import numpy as np
import pandas as pd

exploring the data:
the dataset is imorted fromm scikit learn


In [8]:
from sklearn.datasets import load_iris
iris_dataset=load_iris() 

object returned by load iris is bunch object ,similar to dictionary

In [10]:
print("keys of iris_dataset: \n{}".format(iris_dataset.keys()))

keys of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


DESCR is short description of dataset 

In [11]:
print(iris_dataset['DESCR'][:193]+"\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


lets move on to target names 

In [12]:
print("target names: {}".format(iris_dataset['target_names']))

target names: ['setosa' 'versicolor' 'virginica']


nest line is feature_ names 
value of feature names is list of strings 

In [13]:
print("feature names: {}".format(iris_dataset['feature_names']))

feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


the data we are going to use itself contains in the target and data fields .the data contains nummeric measuremnts of sepal legth ,width and petal length and width in Numpy array:

In [15]:
print("types of data: {}".format(type(iris_dataset['data'])))

types of data: <class 'numpy.ndarray'>


rows od data array corresponds to flowers,while the columnn represents the four measurements that  were  taken for each flower:  

In [16]:
print("shape of data : {}".format(iris_dataset['data'].shape))

shape of data : (150, 4)


first five data samples are printed below

In [17]:
print("First five columns of data:\n{}".format(iris_dataset['data'][:5]))

First five columns of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


from this data we can see that all first five   flowers  have petal width of 0.2 cm     and the    fisrt flower   has    the   longest sepal at  5.1  cm.so  we    can   make output    in     form  of tables and  hence   we  can   understand  which   column  represents which  feature   

In [18]:
print("type of target: {}".format(type(iris_dataset['target'])))

type of target: <class 'numpy.ndarray'>


target is one-dimensional array  and   on   seeing   the  shae    we  can  see    that    it   conatains oen  entry er flower :

In [20]:
print("shape of target: {}".format(iris_dataset['target'].shape))

shape of target: (150,)


In [22]:
print("target:\n{}".format(iris_dataset['target']))

target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


the  meanings of the numbers are  given  by  the  iris ['target_names']array:0   means setosa;1 means  versicolor,and  2  means  virginica

**Training and   testing    the     data:**

In [27]:
import sklearn
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(iris_dataset['data'],iris_dataset['target'],random_state=0)

Before making the   split    ,the train_test _split function shuffle the dataset using a psuedorandom number generator .X_train contains 75% of the rows of the dataset and remaining in  the X_test.

In [28]:
print("X_train shape:{}".format(X_train.shape))
print("Y_train shape:{}".format(Y_train.shape))
print("X_test shape:{}".format(X_test.shape))
print("Y_test shape:{}".format(Y_test.shape))

X_train shape:(112, 4)
Y_train shape:(112,)
X_test shape:(38, 4)
Y_test shape:(38,)


**Inspecting the Data:**
implementing the k-neighbor 

In [29]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)

building the model on training set

In [30]:
knn.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

**Making predictions**
we can now make the redictions using this  model on new data for which we might not know the correct labels.imagine found an iris in wild with the below given data.we can put this data into numy array 

In [31]:
X_new=np.array([[5,2.9,1,.2]])
print("X_new.shape:{}".format(X_new.shape))

X_new.shape:(1, 4)


to  make  a prediction,we call the predict method of  the knn object

In [32]:
prediction=knn.predict(X_new)

print("prediction :{}".format(prediction))
print("predicted target name:{}".format(iris_dataset['target_names'][prediction]))

prediction :[0]
predicted target name:['setosa']


**Evaluatingthe Model**
this is where the test set that we created earlier comes in.this data was not used to build  the  model ,but we do know what the correct species is for each iris in the test set.
therefore we can make a rediction for each  iris in the test data and comare it against its label.

In [33]:
y_pred=knn.predict(X_test)
print("test set predictions :\n {}".format(y_pred))

test set predictions :
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [36]:
print("test set score : {}".format(np.mean(y_pred==Y_test)))

test set score : 0.9736842105263158
